apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodesets.kagebunshin.sh
spec:
  group: kagebunshin.sh
  names:
    plural: nodesets
    singular: nodeset
    kind: NodeSet
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
                priority::
                  type: integer
                provisionTarger:
                  type: integer
                expirationWindow:
                  type: integer
                consolidationTarget:
                  type: integer
                consolidationOptions:
                  type: array
                  items:
                    type: string
                market:
                  type: array
                  items:
                    type: string
                nodeConfRef:
                  type: object

            required:
              - types
              - market
              - cloudConfig
      subresources:
        status: {}

