apiVersion: apps/v1
kind: Deployment
metadata:
  name: medium-deployment
  labels:
    app: medium-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medium-app
  template:
    metadata:
      labels:
        app: medium-app
    spec:
      containers:
      - name: medium-container
        image: nginx
        resources:
          requests:
            cpu: "1"
            memory: "1200Mi"
          limits:
            cpu: "2"
            memory: "2400Mi"

